#SPDX-License-Identifier: MIT-0
---
# tasks file for vlan
  - name: create new user account juniper
    junipernetworks.junos.junos_user:
      name: "{{ juniper.user }}"
      role: super-user
      sshkey: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
      state: present
    when: ansible_network_os == 'junipernetworks.junos.junos'

  - name: Create a new user cisco
    cisco.ios.ios_user:
      name: "{{ cisco.user }}"
      nopassword: true
      sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      state: present
    when: ansible_network_os == 'cisco.ios.ios'

  - name: create a new user
    arista.eos.eos_user:
      name: "{{ arista.user }}"
      sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      state: present
    when: ansible_network_os == 'arista.eos.eos'
